default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: matiasmainder
  password: Mainder
  host: localhost

development:
  <<: *default
  database: positions_api_development

test:
  <<: *default
  database: positions_api_test

production:
  <<: *default
  database: positions_api_production
  username: <tu_usuario_postgres_producción>
  password: <tu_contraseña_postgres_producción>
